variables:
  TF_ROOT: ${CI_PROJECT_DIR}

before_script:
  - cd ${TF_ROOT}
  - echo ${TF_ROOT}

stages:
  - lintsec
  - validate
  - plan

tfseclint:
  stage: lintsec
  image:
    name: $GITLAB_INFRA_REGISTRY/$INFRA_AWS/tfsec:$TFSEC_VERSION
    entrypoint: [""]
  script:
    - echo "Running security scanning on terraform project"
    - tfsec .
  allow_failure: true

terraform_validate:
  stage: validate
  needs: [tfseclint]
  image: 
    name: $GITLAB_INFRA_REGISTRY/$INFRA_AWS/terraform:$TERRAFORM_VERSION
    entrypoint: 
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID_TEST_ENV}' 
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_TEST_ENV}'
  before_script:
    - rm -rf *.terraform*
    - terraform --version
    - pwd
    - terraform init ${TF_ROOT}/test-s3
  script: 
    - pwd
    - terraform validate 

terraform_plan:
  stage: plan
  needs: [terraform_validate]
  image: 
    name: $GITLAB_INFRA_REGISTRY/noah-energy/infra_aws/terraform:$TERRAFORM_VERSION
    entrypoint: 
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID_TEST_ENV}' 
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_TEST_ENV}'
  script:
    - terraform plan 
