variables:
  TERRAFORM_VERSION: "1.1.0"
stages:
  - build-docker
#  - test
#  - production

build terraform image:
  stage: build-docker
  #image: docker:latest
  image: 
    name: hashicorp/terraform:$TERRAFORM_VERSION
    entrypoint: [""]
  script: 
    - terraform --version
    - terraform --help

#deploy to test:
#  stage: test
#  environment: test

#deploy to prod:
#  stage: prod
#  environment: prod