# Include variables and stages
# from noah-pipelines-templates project 
include:
  - project: 'noah-energy/noah-pipelines-templates'
    file:    'variables.yml'
  - project: 'noah-energy/noah-pipelines-templates'
    file:    'terraform_tmpl.yml'

# Stage availables for this pipeline
stages:
  - run-security-scan 
  - infrastructure

# Runs tfsec module scan from noah-pipelines-templates project
run-security-scan:
  stage: run-security-scan
  extends: .module_security_scan
  variables:
    PATH_TO_SCAN: "test-s3/s3"
  script: 
    - echo "Starting Terraform module security scan"

# Run terraform template job from noah-pipelines-templates project
infrastructure:
  stage: infrastructure
  extends: .terraform
  variables:
    AWS_PROFILE_ENV: $TF_USER_TEST_ENV
  script:
    - echo "Testing s3 bucket module creation"
    - cd test-s3/
    - pwd
    - terraform init
    - terraform plan 
