variables:
  TERRAFORM_VERSION: "1.1.0"
  DOCKER_HOST: tcp://docker:2378
stages:
  - registry_login 
  - lintsec
  - validate
  - plan

docker_login:
  stage: registry_login
  image: 
    name: docker:20
    entrypoint: ["/bin/sh", "-c"]
  script: 
    - echo $GITLAB_INFRA_REGISTRY
    - docker login $GITLAB_INFRA_REGISTRY -u marco202 -p $GITLAB_INFRA_REGITRY_TOKEN

tfseclint:
  stage: lintsec
  needs: [docker_login]
  image:
    name: aquasec/tfsec:latest
    entrypoint: [""]
  script:
    - echo "Running security scanning on terraform project"
    - tfsec test-s3
  allow_failure: true

terraform_validate:
  stage: validate
  needs: [tfseclint]
  image: 
    name: hashicorp/terraform:$TERRAFORM_VERSION
    entrypoint: 
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' 
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
  before_script:
    - rm -rf *.terraform*
    - terraform --version
    - terraform init
  script: 
    - terraform validate

terraform_plan:
  stage: plan
  needs: [terraform_validate]
  image: 
    name: hashicorp/terraform:$TERRAFORM_VERSION
    entrypoint: 
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' 
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
  script:
    - terraform plan 
