variables:
  TERRAFORM_VERSION: "1.1.0"
stages:
  - build-docker
#  - test
#  - production

build terraform image:
  stage: build-docker
  image: 
    name: hashicorp/terraform:$TERRAFORM_VERSION
    entrypoint: [""]
  script: 
    - terraform --version
    - terraform --help

workflow:
  rules:
    - if $CI_COMMIT_BRANCH =~ /develop/
      script:
        - echo "I did run from develop branch"
#deploy to test:
#  stage: test
#  environment: test

#deploy to prod:
#  stage: prod
#  environment: prod