# Include variables and stages
# from noah-pipelines-templates project 
include:
  - project: 'noah-energy/noah-pipelines-templates'
    file:    'variables.yml'
  - project: 'noah-energy/noah-pipelines-templates'
    file:    'terraform_tmpl.yml'

# Stage availables for this pipeline
stages:
  - run-security-scan 
  - infrastructure

# Runs tfsec module scan from noah-pipelines-templates project
run-security-scan:
  stage: run-security-scan
  extends: .module_security_scan
  variables:
    PATH_TO_SCAN: "environments/test/"
  script: 
    - echo "Starting Terraform module security scan"

# Run terraform template job from noah-pipelines-templates project
infrastructure:
  stage: infrastructure
  extends: .terraform
  variables:
    AWS_PROFILE_ENV: $TF_USER_TEST_ENV
  script:
    - echo "Creating AWS Infra"
    - cd environments/test/
    - pwd
    - terraform init
    - terraform plan -var-file=test.tfvars -var="db_master_username=$POSTGRES_USER_TEST_ENV" -var="db_master_password=$POSTGRES_PASSWORD_TEST_ENV"
    - terraform apply -var-file=test.tfvars -var="db_master_username=$POSTGRES_USER_TEST_ENV" -var="db_master_password=$POSTGRES_PASSWORD_TEST_ENV" -auto-approve 
    #- terraform destroy -var-file=s3/s3.tfvars -auto-approve
  rules:
    - if: $CI_COMMIT_REF_NAME == 'develop'
  
