variables:
  TERRAFORM_VERSION: "1.1.0"
stages:
  - lintsec


seclinttf:
  stage: lintsec
  image:
    name: aquasec/tfsec:latest
    entrypoint: [""]
  script:
    - echo "Running security scanning on terraform project"
    - tfsec eu-west-1
  allow_failure: true
