stages:
  #- lintsec
  - validate

#tfseclint:
#  stage: lintsec
#  image:
#    name: $GITLAB_INFRA_REGISTRY/$INFRA_AWS/tfsec:$TFSEC_VERSION
#    entrypoint: [""]
#  script:
#    - echo "Running security scanning on terraform project"
#    - tfsec .
#  allow_failure: true

terraform_validate:
  stage: validate
  #needs: [tfseclint]
  image: 
    name: $GITLAB_INFRA_REGISTRY/$INFRA_AWS/terraform:$TERRAFORM_VERSION
    entrypoint: 
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
    - 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_TEST_ENV' 
    - 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_TEST_ENV'
    - terraform --version
    - terraform init 
  script: 
    - terraform validate 
    - terraform plan
    - terraform apply -auto-approve

