variables:
  TERRAFORM_VERSION: "1.1.0"
stages:
  - build-docker
#  - test
#  - production

build terraform image:
  stage: build-docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run hashicorp/terraform:"$TERRAFORM_VERSION"



#deploy to test:
#  stage: test
#  environment: test

#deploy to prod:
#  stage: prod
#  environment: prod