variables:
  TERRAFORM_VERSION: "1.1.0"
stages:
  - build-docker
#  - test
#  - production

build terraform image:
  stage: build-docker
  #image: docker:latest
  image: hashicorp/terraform:$TERRAFORM_VERSION
  entrypoint: [""]

  before_script:
    - terraform -help

  #services:
  #  - docker:dind
  script:
    #- docker run hashicorp/terraform:"$TERRAFORM_VERSION"
    - terraform -init


#deploy to test:
#  stage: test
#  environment: test

#deploy to prod:
#  stage: prod
#  environment: prod